### PR TITLE
1.29 support (Graph API)

### PR DESCRIPTION
**Pull request by roydejong**
This PR adds support for Beat Saber 1.29 by targeting GameLift API overrides rather than master server overrides, which are now no longer supported:

- Adds setting and API to override `graphUrl` from the game's network config with a custom URL
- Removes `MasterServerEndPoint` and `DisableGameLift` patches; rather, if we are overriding Graph URL, we now always force GameLift use
- Bumps MpCore version to `1.3.0` and target Beat Saber `1.29.0`

### Cross-dependent related PRs
- https://github.com/BeatTogether/BeatTogether/pull/42
- https://github.com/BeatTogether/BeatTogether.MasterServer/pull/63
- https://github.com/BeatTogether/BeatTogether.DedicatedServer/pull/128

### CODE REVIEW

**Comment by rcelyte** [comment]
I was kind of hoping we could fuse the graph URL and status URL into one web host to simplify configuration 😕 (Official uses a single domain for both as well)

**Comment by roydejong** [comment]
> I was kind of hoping we could fuse the graph URL and status URL into one web host to simplify configuration 😕 (Official uses a single domain for both as well)

I personally think that this adds a bit more flexibility in how server operators want to handle this. 

In BT's case, for example, the status API and Graph API will most likely end up on completely different ports, so some granularity in defining that is desirable.

Nothing here is final though - this is just my proposal and is all open to discussion for sure

**Comment by rcelyte** [comment]
Appears to work perfectly on 1.29.0 :+1: (testing with `UseCustomApiServer("https://master.battletrains.org", "https://master.battletrains.org");`)

**Comment by Kevman95** [comment]
Merging ;)

**Pull request merged**
